### PR TITLE
Clear all connections in SessionManager during HomekitRoot.stop()

### PR DESCRIPTION
**Pull request by timcharper**
This is an attempt to resolve issue #54, which I've observed during development of the Openhab2 homekit addon.

### CODE REVIEW

**Comment by timcharper** [comment]
In order to reduce the turmoil of whitespace diffs, this PR is based on PR #53; we should decide and merge it before merging this, if this patch ends up being the right way to solve issue #54 .

**Comment by beowulfe** [comment]
Just rerunning the CI on this after merging #53, then I'll merge this as well.

**Comment by timcharper** [comment]
@beowulfe I wasn't sure if this was the ideal way to solve this and was hoping to get your opinion on it first; I guess it seemed like a reasonable solution? :)

**Comment by beowulfe** [comment]
@timcharper - yep, I think it's great. I've used checkstyle in the past, but I don't have an opinion on it vs google's.

**Pull request merged**
